### ISSUE TITLE
Automate downloads of packages

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltkv1#23]
Following from Todd's recommendation to look at how to download models outside of our ecosystem (something we haven't done before). I prefer to give users some assent and information on what is getting downloaded to their local machine. But that can make for a clumsy user experience, too. Note that whatever we do, it ideally would not require any extra server infrastructure on our part but rely solely on github.

On another note, are we happy with the import methods used to date? I have long wanted to refactor that code, even if we keep its interface as-is.

**Comment by todd-cook** [comment]
Are there certain default corpora or libraries that we want to auto fetch and install if the user doesn't specify any? 
This is the approach that Stanford NLP (and many others) is using and I think it's good baseline to guarantee providing something that always basically just works. Users can always customize later. Unless I hear otherwise, I'll wire something up and we can adjust it during review or later.

**Comment by kylepjohnson** [comment]
> Are there certain default corpora or libraries that we want to auto fetch and install if the user doesn't specify any?

Todd, please run with it and do what you believe is right.

 A little on my perspective:

- I like using Git/GitHub to manage our cltk-specific dependencies
- I prefer language-specific repos (eg https://github.com/cltk/latin_models_cltk )
- For dependencies external to the CLTK (stanfordnlp is the big one), I don't know whether we should re-host these or to simply pull from their source. These days, I am leaning towards fetching straight from them.
  + Side note: For stanfordnlp I have been storing files in `~/stanfordnlp_resources`, however this could be moved to our default `~/cltk_data` dir.
- Concerning pre-fetching things, I am ambivalent. Models? For Latin and Greek, that might make sense. Corpora? Maybe, depends on the size of the corpora, in part, maybe. One key thing is that whenever a user is missing some asset, we need to do raise meaningful messages that help our users understand exactly what to do fix the issue.

If you and I majorly deviate on something above, let's talk about it. But again, I trust your instincts.

Also, I have done the following for stanfordnlp, which may or may not be of use to you:

- https://github.com/cltk/cltkv1/blob/master/scripts/download_misc_dependencies.py
- https://github.com/cltk/cltkv1/blob/31584e4c12153612511fb4c984c7db50df751dd7/src/cltkv1/wrappers/stanford.py#L191

**Comment by kylepjohnson** [comment]
Download for w2v: https://github.com/cltk/cltkv1/blob/35bf1fe64a8a62711ada05112b42ef545d4fe5a2/src/cltkv1/embeddings/embeddings.py#L307

for stanfordnlp: https://github.com/cltk/cltkv1/blob/35bf1fe64a8a62711ada05112b42ef545d4fe5a2/src/cltkv1/dependency/stanford.py#L204

Crossing fingers these links will stay up. I'll think of some backups, too.
