### ISSUE TITLE
Build docs on RTD

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltkv1#25]
The build on RTD gave me no end of troubles, due to something with stanfordnlp. Whether it was failing to download the models or the package was too slow to build or whatever, I forget.

Example of what's currently done: https://readthedocs.org/projects/cltk/builds/

They have an improved system now where instead of configs in their website you add a `readthedocs.yml`: https://docs.readthedocs.io/en/stable/config-file/v2.html

Edit:

This method might cause hangs, too, and could perhaps be removed for now: https://github.com/cltk/cltkv1/blob/master/src/cltkv1/wrappers/stanford.py#L202

**Comment by kylepjohnson** [comment]
I need to give this a shot again, however @free-variation if you're in the mood this would be a big help for sharing w/ people at the conference.

But if you find yourself falling into configuration hell, then please stress yourself about it.

**Comment by free-variation** [comment]
Looking into it now @kylepjohnson .

**Comment by free-variation** [comment]
@kylepjohnson I don't really know what I'm doing.  I created a user at RTD, and then a new project to build the docks for cltkv1, by pointing to that repo.

It built fine and docs are visible here: https://cltkv1.readthedocs.io/en/latest/

I didn't have to configure anything, presumably because you already did.  Where is the build hanging for you?

**Comment by kylepjohnson** [comment]
This is good! Before I was getting out of memory errors during the Stanford install. But clearly we're OK now.

Jan 2, 2020, 18:35 by notifications@github.com:

**Comment by free-variation** [comment]
Ah because the models were getting loaded for every parse request, earlier.  Should be ok now, and tests run faster.

**Comment by kylepjohnson** [comment]
Looking good. Please add me and Patrick as maintainers on RTD and I'll close this.

**Comment by free-variation** [comment]
![image](https://user-images.githubusercontent.com/516801/71704984-37614300-2dab-11ea-96eb-95a1beb6e338.png)

If this looks right then you can close.

**Comment by kylepjohnson** [comment]
I forgot, my username on RTD is actually `kyle`. Please add that or my email, instead.

**Comment by free-variation** [comment]
whoops -- I wonder who the other fellow might be :)  In any case, fatto:

![image](https://user-images.githubusercontent.com/516801/71742258-1c381700-2e2f-11ea-9ad7-a1c77271df34.png)

**Comment by kylepjohnson** [comment]
It's a zombie account on RTD that I lost. My documentary doppleganger!

thank you
