### ISSUE TITLE
Finalize access methods to Doc

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltkv1#31]
John, we started talking about this in another thread, seems like the logical next step. You started [the sentences property](https://github.com/cltk/cltkv1/blob/master/src/cltkv1/utils/data_types.py#L90) to `Doc`.

Outstanding questions, seems to me:

* What should the methods be?
* Will these all just process information that has already been generated (eg, getting POS tags) or will there be times when more expensive operations should only be run when needed? I think for example of fasttext embeddings: They'll be downstream of each `Word.string` token, which 9% of our users will want, however the word embeddings might only be asked for by 5% of them.

Candidate methods/properties:
* [x] `Doc.sentences`: List[List[Word]]
* [x] `Doc.sentences_tokens`: List[List[str]]
* [x] `Doc.sentences_strings`:  List[str]
* [x] `Doc.pos_tags`: List[str]
* [x] `Doc.morphosyntactic_features`: List[Dict[str, str]]
* [x] `Doc.lemmata`: List[str]
* [ ] `Doc.stems` (if available)
* [ ] `Doc.embeddings`
* [ ] `Doc.scansion` (this needs some more thinking)
* …
* ?

**Comment by free-variation** [comment]
I've added:

`Doc.pos`
`Doc.features`

Trees are available at `Doc.trees` if one has the `TreeBuilderProcess` in the pipeline.

**Comment by kylepjohnson** [comment]
#34 adds `Doc.lemmata`
