### ISSUE TITLE
Put badges in one row in README.rst

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltkv1#90]
They're appearing on new lines and breaking when putting into one line

**Comment by clemsciences** [comment]
I found this: https://stackoverflow.com/a/42522042/8791925. It may solve your problem.

**Comment by kylepjohnson** [comment]
That was perfect @clemsciences thank you.

BTW would you like to begin testing the new software? I recommend starting with the Germanic languages in the pipeline, which are: `got` (Gothic), `gmh` (Middle High German), `enm` (Middle English), `ang` (Old English), `non` (Old Norse).

And you might know something about `frm` (Middle French) and `fro` (Old French) too ;)

Basic API usage here: https://github.com/cltk/cltkv1#use and here the link to our PIpeline docs: https://cltkv1.readthedocs.io/en/latest/cltk.languages.html#module-cltk.languages.pipelines

Before making any pull request, open up an Issue here or find us on the Discord server.

**Comment by clemsciences** [comment]
Exactly, I have thought about contributing and it's time for this.

**Comment by kylepjohnson** [comment]
We were working very slowly and were not ready for help -- but we definitely are now :)

Let's talk on Discord, the team is around to answer your questions and listen to your ideas!
